begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * UniTime 3.4 (University Timetabling Application)  * Copyright (C) 2012, UniTime LLC, and individual contributors  * as indicated by the @authors tag.  *   * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 3 of the License, or  * (at your option) any later version.  *   * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *   * You should have received a copy of the GNU General Public License along  * with this program.  If not, see<http://www.gnu.org/licenses/>.  *   */
end_comment

begin_package
package|package
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|security
operator|.
name|authority
package|;
end_package

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|ApplicationProperties
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|DepartmentalInstructor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|Student
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|security
operator|.
name|rights
operator|.
name|Right
import|;
end_import

begin_class
specifier|public
class|class
name|StudentAuthority
extends|extends
name|AbstractAuthority
block|{
specifier|private
specifier|static
specifier|final
name|long
name|serialVersionUID
init|=
literal|1L
decl_stmt|;
specifier|public
specifier|static
specifier|final
name|String
name|TYPE
init|=
literal|"Student"
decl_stmt|;
specifier|public
name|StudentAuthority
parameter_list|(
name|Student
name|student
parameter_list|)
block|{
name|super
argument_list|(
name|student
operator|.
name|getUniqueId
argument_list|()
argument_list|,
name|TYPE
argument_list|,
name|student
operator|.
name|getName
argument_list|(
name|DepartmentalInstructor
operator|.
name|sNameFormatLastFirstMiddle
argument_list|)
argument_list|)
expr_stmt|;
block|}
annotation|@
name|Override
specifier|public
name|boolean
name|hasRight
parameter_list|(
name|Right
name|right
parameter_list|)
block|{
switch|switch
condition|(
name|right
condition|)
block|{
case|case
name|SessionDefaultCurrent
case|:
case|case
name|PersonalSchedule
case|:
case|case
name|Inquiry
case|:
case|case
name|Events
case|:
case|case
name|EventDetail
case|:
case|case
name|EventLocation
case|:
case|case
name|EventAddSpecial
case|:
case|case
name|EventEdit
case|:
case|case
name|EventMeetingEdit
case|:
case|case
name|EventDate
case|:
case|case
name|StudentEnrollments
case|:
case|case
name|SchedulingAssistant
case|:
case|case
name|CourseRequests
case|:
return|return
literal|true
return|;
case|case
name|EventEditPast
case|:
return|return
literal|"true"
operator|.
name|equals
argument_list|(
name|ApplicationProperties
operator|.
name|getProperty
argument_list|(
literal|"tmtbl.event.allowEditPast"
argument_list|,
literal|"false"
argument_list|)
argument_list|)
return|;
default|default:
return|return
literal|false
return|;
block|}
block|}
block|}
end_class

end_unit

