begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * UniTime 3.2 (University Timetabling Application)  * Copyright (C) 2008 - 2010, UniTime LLC, and individual contributors  * as indicated by the @authors tag.  *   * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 3 of the License, or  * (at your option) any later version.  *   * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *   * You should have received a copy of the GNU General Public License along  * with this program.  If not, see<http://www.gnu.org/licenses/>.  *   */
end_comment

begin_package
package|package
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|authenticate
operator|.
name|jaas
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashMap
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Map
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|security
operator|.
name|auth
operator|.
name|Subject
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|security
operator|.
name|auth
operator|.
name|callback
operator|.
name|CallbackHandler
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|security
operator|.
name|auth
operator|.
name|spi
operator|.
name|LoginModule
import|;
end_import

begin_class
specifier|public
specifier|abstract
class|class
name|AuthenticateModule
implements|implements
name|LoginModule
block|{
specifier|private
name|Subject
name|subject
init|=
literal|null
decl_stmt|;
specifier|private
name|CallbackHandler
name|callbackHandler
init|=
literal|null
decl_stmt|;
specifier|private
name|Map
name|sharedState
decl_stmt|;
specifier|private
name|Map
name|options
decl_stmt|;
specifier|private
name|boolean
name|authSucceeded
decl_stmt|;
specifier|private
name|boolean
name|commitSucceeded
decl_stmt|;
specifier|private
name|String
name|user
decl_stmt|;
specifier|public
specifier|abstract
name|boolean
name|doAuthenticate
parameter_list|(
name|HashMap
name|userProps
parameter_list|)
throws|throws
name|Exception
function_decl|;
specifier|public
name|void
name|initialize
parameter_list|(
name|Subject
name|subject
parameter_list|,
name|CallbackHandler
name|callbackHandler
parameter_list|,
name|Map
name|sharedState
parameter_list|,
name|Map
name|options
parameter_list|)
block|{
name|setSubject
argument_list|(
name|subject
argument_list|)
expr_stmt|;
name|setCallbackHandler
argument_list|(
name|callbackHandler
argument_list|)
expr_stmt|;
name|setSharedState
argument_list|(
name|sharedState
argument_list|)
expr_stmt|;
name|setOptions
argument_list|(
name|options
argument_list|)
expr_stmt|;
name|setUser
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|setAuthSucceeded
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|setCommitSucceeded
argument_list|(
literal|false
argument_list|)
expr_stmt|;
block|}
specifier|protected
name|void
name|reset
parameter_list|()
block|{
name|setUser
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|setAuthSucceeded
argument_list|(
literal|false
argument_list|)
expr_stmt|;
name|setCommitSucceeded
argument_list|(
literal|false
argument_list|)
expr_stmt|;
block|}
specifier|public
name|boolean
name|isAuthSucceeded
parameter_list|()
block|{
return|return
name|authSucceeded
return|;
block|}
specifier|public
name|void
name|setAuthSucceeded
parameter_list|(
name|boolean
name|authSucceeded
parameter_list|)
block|{
name|this
operator|.
name|authSucceeded
operator|=
name|authSucceeded
expr_stmt|;
block|}
specifier|public
name|CallbackHandler
name|getCallbackHandler
parameter_list|()
block|{
return|return
name|callbackHandler
return|;
block|}
specifier|public
name|void
name|setCallbackHandler
parameter_list|(
name|CallbackHandler
name|callbackHandler
parameter_list|)
block|{
name|this
operator|.
name|callbackHandler
operator|=
name|callbackHandler
expr_stmt|;
block|}
specifier|public
name|boolean
name|isCommitSucceeded
parameter_list|()
block|{
return|return
name|commitSucceeded
return|;
block|}
specifier|public
name|void
name|setCommitSucceeded
parameter_list|(
name|boolean
name|commitSucceeded
parameter_list|)
block|{
name|this
operator|.
name|commitSucceeded
operator|=
name|commitSucceeded
expr_stmt|;
block|}
specifier|public
name|Map
name|getOptions
parameter_list|()
block|{
return|return
name|options
return|;
block|}
specifier|public
name|void
name|setOptions
parameter_list|(
name|Map
name|options
parameter_list|)
block|{
name|this
operator|.
name|options
operator|=
name|options
expr_stmt|;
block|}
specifier|public
name|Map
name|getSharedState
parameter_list|()
block|{
return|return
name|sharedState
return|;
block|}
specifier|public
name|void
name|setSharedState
parameter_list|(
name|Map
name|sharedState
parameter_list|)
block|{
name|this
operator|.
name|sharedState
operator|=
name|sharedState
expr_stmt|;
block|}
specifier|public
name|Subject
name|getSubject
parameter_list|()
block|{
return|return
name|subject
return|;
block|}
specifier|public
name|void
name|setSubject
parameter_list|(
name|Subject
name|subject
parameter_list|)
block|{
name|this
operator|.
name|subject
operator|=
name|subject
expr_stmt|;
block|}
specifier|public
name|String
name|getUser
parameter_list|()
block|{
return|return
name|user
return|;
block|}
specifier|public
name|void
name|setUser
parameter_list|(
name|String
name|user
parameter_list|)
block|{
name|this
operator|.
name|user
operator|=
name|user
expr_stmt|;
block|}
block|}
end_class

end_unit

