begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to The Apereo Foundation under one or more contributor license  * agreements. See the NOTICE file distributed with this work for  * additional information regarding copyright ownership.  *  * The Apereo Foundation licenses this file to you under the Apache License,  * Version 2.0 (the "License"); you may not use this file except in  * compliance with the License. You may obtain a copy of the License at:  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *  * See the License for the specific language governing permissions and  * limitations under the License.  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|action
package|;
end_package

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|ArrayList
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Collections
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashSet
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Iterator
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|List
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Vector
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|servlet
operator|.
name|http
operator|.
name|HttpServletRequest
import|;
end_import

begin_import
import|import
name|javax
operator|.
name|servlet
operator|.
name|http
operator|.
name|HttpServletResponse
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|struts
operator|.
name|action
operator|.
name|ActionForm
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|struts
operator|.
name|action
operator|.
name|ActionForward
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|struts
operator|.
name|action
operator|.
name|ActionMapping
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|struts
operator|.
name|action
operator|.
name|ActionMessages
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|struts
operator|.
name|action
operator|.
name|ActionRedirect
import|;
end_import

begin_import
import|import
name|org
operator|.
name|apache
operator|.
name|struts
operator|.
name|util
operator|.
name|MessageResources
import|;
end_import

begin_import
import|import
name|org
operator|.
name|hibernate
operator|.
name|Transaction
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|beans
operator|.
name|factory
operator|.
name|annotation
operator|.
name|Autowired
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|stereotype
operator|.
name|Service
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|commons
operator|.
name|Debug
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|localization
operator|.
name|impl
operator|.
name|Localization
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|localization
operator|.
name|messages
operator|.
name|CourseMessages
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|defaults
operator|.
name|ApplicationProperty
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|defaults
operator|.
name|CommonValues
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|defaults
operator|.
name|UserProperty
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|form
operator|.
name|ClassEditForm
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|interfaces
operator|.
name|ExternalClassEditAction
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|ChangeLog
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|ClassInstructor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|Class_
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|CourseOffering
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|DatePattern
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|DatePatternPref
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|Department
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|DepartmentalInstructor
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|Preference
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|PreferenceLevel
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|SchedulingSubpart
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|StudentAccomodation
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|TeachingClassRequest
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|TimePattern
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|comparators
operator|.
name|InstructorComparator
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|dao
operator|.
name|Class_DAO
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|dao
operator|.
name|DatePatternDAO
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|dao
operator|.
name|DepartmentalInstructorDAO
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|dao
operator|.
name|TeachingResponsibilityDAO
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|security
operator|.
name|SessionContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|security
operator|.
name|rights
operator|.
name|Right
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|util
operator|.
name|LookupTables
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|webutil
operator|.
name|BackTracker
import|;
end_import

begin_comment
comment|/**  * MyEclipse Struts  * Creation date: 12-08-2005  *  * XDoclet definition:  * @struts:action path="/classEdit" name="classEditForm" input="/user/classEdit.jsp" scope="request" validate="true"  *  * @author Tomas Muller, Zuzana Mullerova, Stephanie Schluttenhofer  */
end_comment

begin_class
annotation|@
name|Service
argument_list|(
literal|"/classEdit"
argument_list|)
specifier|public
class|class
name|ClassEditAction
extends|extends
name|PreferencesAction
block|{
specifier|protected
specifier|final
specifier|static
name|CourseMessages
name|MSG
init|=
name|Localization
operator|.
name|create
argument_list|(
name|CourseMessages
operator|.
name|class
argument_list|)
decl_stmt|;
annotation|@
name|Autowired
name|SessionContext
name|sessionContext
decl_stmt|;
comment|// --------------------------------------------------------- Class Constants
comment|/** Anchor names **/
specifier|public
specifier|final
name|String
name|HASH_INSTRUCTORS
init|=
literal|"Instructors"
decl_stmt|;
comment|// --------------------------------------------------------- Methods
comment|/**      * Method execute      * @param mapping      * @param form      * @param request      * @param response      * @return ActionForward      */
specifier|public
name|ActionForward
name|execute
parameter_list|(
name|ActionMapping
name|mapping
parameter_list|,
name|ActionForm
name|form
parameter_list|,
name|HttpServletRequest
name|request
parameter_list|,
name|HttpServletResponse
name|response
parameter_list|)
throws|throws
name|Exception
block|{
try|try
block|{
name|super
operator|.
name|execute
argument_list|(
name|mapping
argument_list|,
name|form
argument_list|,
name|request
argument_list|,
name|response
argument_list|)
expr_stmt|;
name|ClassEditForm
name|frm
init|=
operator|(
name|ClassEditForm
operator|)
name|form
decl_stmt|;
name|MessageResources
name|rsc
init|=
name|getResources
argument_list|(
name|request
argument_list|)
decl_stmt|;
name|ActionMessages
name|errors
init|=
operator|new
name|ActionMessages
argument_list|()
decl_stmt|;
comment|// Read parameters
name|String
name|classId
init|=
name|request
operator|.
name|getParameter
argument_list|(
literal|"cid"
argument_list|)
operator|==
literal|null
condition|?
name|request
operator|.
name|getAttribute
argument_list|(
literal|"cid"
argument_list|)
operator|!=
literal|null
condition|?
name|request
operator|.
name|getAttribute
argument_list|(
literal|"cid"
argument_list|)
operator|.
name|toString
argument_list|()
else|:
literal|null
else|:
name|request
operator|.
name|getParameter
argument_list|(
literal|"cid"
argument_list|)
decl_stmt|;
name|String
name|reloadCause
init|=
name|request
operator|.
name|getParameter
argument_list|(
literal|"reloadCause"
argument_list|)
decl_stmt|;
name|String
name|op
init|=
name|frm
operator|.
name|getOp
argument_list|()
decl_stmt|;
if|if
condition|(
name|request
operator|.
name|getParameter
argument_list|(
literal|"op2"
argument_list|)
operator|!=
literal|null
operator|&&
name|request
operator|.
name|getParameter
argument_list|(
literal|"op2"
argument_list|)
operator|.
name|length
argument_list|()
operator|>
literal|0
condition|)
name|op
operator|=
name|request
operator|.
name|getParameter
argument_list|(
literal|"op2"
argument_list|)
expr_stmt|;
comment|// Read class id from form
if|if
condition|(
comment|//op.equals(rsc.getMessage("button.reload"))||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionAddTimePreference
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionAddRoomPreference
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionAddBuildingPreference
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionAddRoomFeaturePreference
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionAddDistributionPreference
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionAddInstructor
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionUpdatePreferences
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionAddDatePatternPreference
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionAddAttributePreference
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionAddInstructorPreference
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|rsc
operator|.
name|getMessage
argument_list|(
literal|"button.cancel"
argument_list|)
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionClearClassPreferences
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionRemoveBuildingPreference
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionRemoveDistributionPreference
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionRemoveRoomFeaturePreference
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionRemoveRoomGroupPreference
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionRemoveRoomPreference
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionRemoveDatePatternPreference
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionRemoveTimePattern
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionRemoveInstructor
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionRemoveAttributePreference
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionRemoveInstructorPreference
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|rsc
operator|.
name|getMessage
argument_list|(
literal|"button.changeOwner"
argument_list|)
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionAddRoomGroupPreference
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionBackToDetail
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionNextClass
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionPreviousClass
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
literal|"updateDatePattern"
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
literal|"updatePref"
argument_list|)
condition|)
block|{
name|classId
operator|=
name|frm
operator|.
name|getClassId
argument_list|()
operator|.
name|toString
argument_list|()
expr_stmt|;
block|}
comment|// Determine if initial load
if|if
condition|(
name|op
operator|==
literal|null
operator|||
name|op
operator|.
name|trim
argument_list|()
operator|.
name|length
argument_list|()
operator|==
literal|0
operator|||
operator|(
name|request
operator|.
name|getAttribute
argument_list|(
literal|"cs"
argument_list|)
operator|!=
literal|null
operator|&&
name|request
operator|.
name|getAttribute
argument_list|(
literal|"cs"
argument_list|)
operator|.
name|toString
argument_list|()
operator|.
name|equals
argument_list|(
literal|"classOwnerChange"
argument_list|)
operator|)
condition|)
block|{
name|op
operator|=
literal|"init"
expr_stmt|;
block|}
comment|// Check op exists
if|if
condition|(
name|op
operator|==
literal|null
operator|||
name|op
operator|.
name|trim
argument_list|()
operator|==
literal|""
condition|)
throw|throw
operator|new
name|Exception
argument_list|(
name|MSG
operator|.
name|errorNullOperationNotSupported
argument_list|()
argument_list|)
throw|;
name|boolean
name|timeVertical
init|=
name|CommonValues
operator|.
name|VerticalGrid
operator|.
name|eq
argument_list|(
name|sessionContext
operator|.
name|getUser
argument_list|()
operator|.
name|getProperty
argument_list|(
name|UserProperty
operator|.
name|GridOrientation
argument_list|)
argument_list|)
decl_stmt|;
name|Debug
operator|.
name|debug
argument_list|(
literal|"op: "
operator|+
name|op
argument_list|)
expr_stmt|;
name|Debug
operator|.
name|debug
argument_list|(
literal|"class: "
operator|+
name|classId
argument_list|)
expr_stmt|;
name|Debug
operator|.
name|debug
argument_list|(
literal|"reload cause: "
operator|+
name|reloadCause
argument_list|)
expr_stmt|;
comment|// Check class exists
if|if
condition|(
name|classId
operator|==
literal|null
operator|||
name|classId
operator|.
name|trim
argument_list|()
operator|.
name|length
argument_list|()
operator|==
literal|0
condition|)
block|{
if|if
condition|(
name|BackTracker
operator|.
name|doBack
argument_list|(
name|request
argument_list|,
name|response
argument_list|)
condition|)
return|return
literal|null
return|;
else|else
throw|throw
operator|new
name|Exception
argument_list|(
name|MSG
operator|.
name|errorClassInfoNotSupplied
argument_list|()
argument_list|)
throw|;
block|}
name|sessionContext
operator|.
name|checkPermission
argument_list|(
name|classId
argument_list|,
literal|"Class_"
argument_list|,
name|Right
operator|.
name|ClassEdit
argument_list|)
expr_stmt|;
comment|// Change Owner - Go back to Change Owner Screen
if|if
condition|(
name|op
operator|.
name|equals
argument_list|(
name|rsc
operator|.
name|getMessage
argument_list|(
literal|"button.changeOwner"
argument_list|)
argument_list|)
operator|&&
name|classId
operator|!=
literal|null
operator|&&
name|classId
operator|.
name|trim
argument_list|()
operator|.
name|length
argument_list|()
operator|!=
literal|0
condition|)
block|{
name|request
operator|.
name|setAttribute
argument_list|(
literal|"classId"
argument_list|,
name|classId
argument_list|)
expr_stmt|;
return|return
name|mapping
operator|.
name|findForward
argument_list|(
literal|"changeClassOwner"
argument_list|)
return|;
block|}
comment|// Cancel - Go back to Class Detail Screen
if|if
condition|(
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionBackToDetail
argument_list|()
argument_list|)
operator|&&
name|classId
operator|!=
literal|null
operator|&&
name|classId
operator|.
name|trim
argument_list|()
operator|.
name|length
argument_list|()
operator|!=
literal|0
condition|)
block|{
name|ActionRedirect
name|redirect
init|=
operator|new
name|ActionRedirect
argument_list|(
name|mapping
operator|.
name|findForward
argument_list|(
literal|"displayClassDetail"
argument_list|)
argument_list|)
decl_stmt|;
name|redirect
operator|.
name|addParameter
argument_list|(
literal|"cid"
argument_list|,
name|classId
argument_list|)
expr_stmt|;
return|return
name|redirect
return|;
block|}
comment|// If class id is not null - load class info
name|Class_DAO
name|cdao
init|=
operator|new
name|Class_DAO
argument_list|()
decl_stmt|;
name|Class_
name|c
init|=
name|cdao
operator|.
name|get
argument_list|(
name|Long
operator|.
name|valueOf
argument_list|(
name|classId
argument_list|)
argument_list|)
decl_stmt|;
comment|// Add Distribution Preference - Redirect to dist prefs screen
if|if
condition|(
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionAddDistributionPreference
argument_list|()
argument_list|)
condition|)
block|{
name|sessionContext
operator|.
name|checkPermission
argument_list|(
name|c
argument_list|,
name|Right
operator|.
name|DistributionPreferenceClass
argument_list|)
expr_stmt|;
name|SchedulingSubpart
name|ss
init|=
name|c
operator|.
name|getSchedulingSubpart
argument_list|()
decl_stmt|;
name|CourseOffering
name|cco
init|=
name|ss
operator|.
name|getInstrOfferingConfig
argument_list|()
operator|.
name|getControllingCourseOffering
argument_list|()
decl_stmt|;
name|request
operator|.
name|setAttribute
argument_list|(
literal|"subjectAreaId"
argument_list|,
name|cco
operator|.
name|getSubjectArea
argument_list|()
operator|.
name|getUniqueId
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
name|request
operator|.
name|setAttribute
argument_list|(
literal|"schedSubpartId"
argument_list|,
name|ss
operator|.
name|getUniqueId
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
name|request
operator|.
name|setAttribute
argument_list|(
literal|"courseOffrId"
argument_list|,
name|cco
operator|.
name|getUniqueId
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
name|request
operator|.
name|setAttribute
argument_list|(
literal|"classId"
argument_list|,
name|c
operator|.
name|getUniqueId
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
return|return
name|mapping
operator|.
name|findForward
argument_list|(
literal|"addDistributionPrefs"
argument_list|)
return|;
block|}
comment|// Add Instructor
if|if
condition|(
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionAddInstructor
argument_list|()
argument_list|)
condition|)
name|addInstructor
argument_list|(
name|request
argument_list|,
name|frm
argument_list|,
name|errors
argument_list|)
expr_stmt|;
comment|// Delete Instructor
if|if
condition|(
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionRemoveInstructor
argument_list|()
argument_list|)
operator|&&
name|request
operator|.
name|getParameter
argument_list|(
literal|"deleteType"
argument_list|)
operator|!=
literal|null
operator|&&
name|request
operator|.
name|getParameter
argument_list|(
literal|"deleteType"
argument_list|)
operator|.
name|equals
argument_list|(
literal|"instructor"
argument_list|)
condition|)
name|deleteInstructor
argument_list|(
name|request
argument_list|,
name|frm
argument_list|)
expr_stmt|;
comment|// Restore all inherited preferences
if|if
condition|(
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionClearClassPreferences
argument_list|()
argument_list|)
condition|)
block|{
name|sessionContext
operator|.
name|checkPermission
argument_list|(
name|c
argument_list|,
name|Right
operator|.
name|ClassEditClearPreferences
argument_list|)
expr_stmt|;
name|Set
name|s
init|=
name|c
operator|.
name|getPreferences
argument_list|()
decl_stmt|;
name|doClear
argument_list|(
name|s
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|TIME
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|ROOM
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|ROOM_FEATURE
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|ROOM_GROUP
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|BUILDING
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|DATE
argument_list|)
expr_stmt|;
name|c
operator|.
name|setPreferences
argument_list|(
name|s
argument_list|)
expr_stmt|;
name|cdao
operator|.
name|update
argument_list|(
name|c
argument_list|)
expr_stmt|;
name|op
operator|=
literal|"init"
expr_stmt|;
name|ChangeLog
operator|.
name|addChange
argument_list|(
literal|null
argument_list|,
name|sessionContext
argument_list|,
name|c
argument_list|,
name|ChangeLog
operator|.
name|Source
operator|.
name|CLASS_EDIT
argument_list|,
name|ChangeLog
operator|.
name|Operation
operator|.
name|CLEAR_PREF
argument_list|,
name|c
operator|.
name|getSchedulingSubpart
argument_list|()
operator|.
name|getInstrOfferingConfig
argument_list|()
operator|.
name|getInstructionalOffering
argument_list|()
operator|.
name|getControllingCourseOffering
argument_list|()
operator|.
name|getSubjectArea
argument_list|()
argument_list|,
name|c
operator|.
name|getManagingDept
argument_list|()
argument_list|)
expr_stmt|;
name|ActionRedirect
name|redirect
init|=
operator|new
name|ActionRedirect
argument_list|(
name|mapping
operator|.
name|findForward
argument_list|(
literal|"displayClassDetail"
argument_list|)
argument_list|)
decl_stmt|;
name|redirect
operator|.
name|addParameter
argument_list|(
literal|"cid"
argument_list|,
name|classId
argument_list|)
expr_stmt|;
return|return
name|redirect
return|;
block|}
comment|// Reset form for initial load
if|if
condition|(
name|op
operator|.
name|equals
argument_list|(
literal|"init"
argument_list|)
condition|)
block|{
name|frm
operator|.
name|reset
argument_list|(
name|mapping
argument_list|,
name|request
argument_list|)
expr_stmt|;
block|}
comment|// Load form attributes that are constant
name|doLoad
argument_list|(
name|request
argument_list|,
name|frm
argument_list|,
name|c
argument_list|,
name|op
argument_list|)
expr_stmt|;
comment|// Update Preferences for Class
if|if
condition|(
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionUpdatePreferences
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionNextClass
argument_list|()
argument_list|)
operator|||
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionPreviousClass
argument_list|()
argument_list|)
condition|)
block|{
comment|// Validate input prefs
name|errors
operator|=
name|frm
operator|.
name|validate
argument_list|(
name|mapping
argument_list|,
name|request
argument_list|)
expr_stmt|;
comment|// No errors - Add to class and update
if|if
condition|(
name|errors
operator|.
name|size
argument_list|()
operator|==
literal|0
condition|)
block|{
name|org
operator|.
name|hibernate
operator|.
name|Session
name|hibSession
init|=
name|cdao
operator|.
name|getSession
argument_list|()
decl_stmt|;
name|Transaction
name|tx
init|=
name|hibSession
operator|.
name|beginTransaction
argument_list|()
decl_stmt|;
try|try
block|{
comment|// Clear all old prefs
name|Set
name|s
init|=
name|c
operator|.
name|getPreferences
argument_list|()
decl_stmt|;
name|doClear
argument_list|(
name|s
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|TIME
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|ROOM
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|ROOM_FEATURE
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|ROOM_GROUP
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|BUILDING
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|DATE
argument_list|)
expr_stmt|;
comment|// Save class data
name|doUpdate
argument_list|(
name|request
argument_list|,
name|frm
argument_list|,
name|c
argument_list|,
name|hibSession
argument_list|)
expr_stmt|;
comment|// Save Prefs
name|super
operator|.
name|doUpdate
argument_list|(
name|request
argument_list|,
name|frm
argument_list|,
name|c
argument_list|,
name|s
argument_list|,
name|timeVertical
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|TIME
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|ROOM
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|ROOM_FEATURE
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|ROOM_GROUP
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|BUILDING
argument_list|,
name|Preference
operator|.
name|Type
operator|.
name|DATE
argument_list|)
expr_stmt|;
name|hibSession
operator|.
name|saveOrUpdate
argument_list|(
name|c
argument_list|)
expr_stmt|;
name|tx
operator|.
name|commit
argument_list|()
expr_stmt|;
name|String
name|className
init|=
name|ApplicationProperty
operator|.
name|ExternalActionClassEdit
operator|.
name|value
argument_list|()
decl_stmt|;
if|if
condition|(
name|className
operator|!=
literal|null
operator|&&
name|className
operator|.
name|trim
argument_list|()
operator|.
name|length
argument_list|()
operator|>
literal|0
condition|)
block|{
name|ExternalClassEditAction
name|editAction
init|=
operator|(
name|ExternalClassEditAction
operator|)
operator|(
name|Class
operator|.
name|forName
argument_list|(
name|className
argument_list|)
operator|.
name|getDeclaredConstructor
argument_list|()
operator|.
name|newInstance
argument_list|()
operator|)
decl_stmt|;
name|editAction
operator|.
name|performExternalClassEditAction
argument_list|(
name|c
argument_list|,
name|hibSession
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionNextClass
argument_list|()
argument_list|)
condition|)
block|{
name|response
operator|.
name|sendRedirect
argument_list|(
name|response
operator|.
name|encodeURL
argument_list|(
literal|"classEdit.do?cid="
operator|+
name|frm
operator|.
name|getNextId
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
return|return
literal|null
return|;
block|}
if|if
condition|(
name|op
operator|.
name|equals
argument_list|(
name|MSG
operator|.
name|actionPreviousClass
argument_list|()
argument_list|)
condition|)
block|{
name|response
operator|.
name|sendRedirect
argument_list|(
name|response
operator|.
name|encodeURL
argument_list|(
literal|"classEdit.do?cid="
operator|+
name|frm
operator|.
name|getPreviousId
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
return|return
literal|null
return|;
block|}
name|ActionRedirect
name|redirect
init|=
operator|new
name|ActionRedirect
argument_list|(
name|mapping
operator|.
name|findForward
argument_list|(
literal|"displayClassDetail"
argument_list|)
argument_list|)
decl_stmt|;
name|redirect
operator|.
name|addParameter
argument_list|(
literal|"cid"
argument_list|,
name|classId
argument_list|)
expr_stmt|;
return|return
name|redirect
return|;
block|}
catch|catch
parameter_list|(
name|Exception
name|e
parameter_list|)
block|{
name|tx
operator|.
name|rollback
argument_list|()
expr_stmt|;
throw|throw
name|e
throw|;
block|}
block|}
else|else
block|{
name|saveErrors
argument_list|(
name|request
argument_list|,
name|errors
argument_list|)
expr_stmt|;
block|}
block|}
name|Vector
name|leadInstructors
init|=
operator|new
name|Vector
argument_list|()
decl_stmt|;
if|if
condition|(
name|op
operator|.
name|equals
argument_list|(
literal|"updatePref"
argument_list|)
condition|)
block|{
try|try
block|{
name|List
name|instrLead
init|=
name|frm
operator|.
name|getInstrLead
argument_list|()
decl_stmt|;
name|List
name|instructors
init|=
name|frm
operator|.
name|getInstructors
argument_list|()
decl_stmt|;
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|instructors
operator|.
name|size
argument_list|()
condition|;
name|i
operator|++
control|)
block|{
name|String
name|instrId
init|=
name|instructors
operator|.
name|get
argument_list|(
name|i
argument_list|)
operator|.
name|toString
argument_list|()
decl_stmt|;
if|if
condition|(
name|Preference
operator|.
name|BLANK_PREF_VALUE
operator|.
name|equals
argument_list|(
name|instrId
argument_list|)
condition|)
continue|continue;
name|boolean
name|lead
init|=
literal|"on"
operator|.
name|equals
argument_list|(
name|instrLead
operator|.
name|get
argument_list|(
name|i
argument_list|)
argument_list|)
decl_stmt|;
if|if
condition|(
name|lead
condition|)
name|leadInstructors
operator|.
name|add
argument_list|(
operator|(
operator|new
name|DepartmentalInstructorDAO
argument_list|()
operator|)
operator|.
name|get
argument_list|(
name|Long
operator|.
name|valueOf
argument_list|(
name|instrId
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|op
operator|=
literal|"init"
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|NumberFormatException
name|e
parameter_list|)
block|{
block|}
block|}
if|if
condition|(
name|op
operator|.
name|equals
argument_list|(
literal|"updateDatePattern"
argument_list|)
condition|)
block|{
name|initPrefs
argument_list|(
name|frm
argument_list|,
name|c
argument_list|,
name|leadInstructors
argument_list|,
literal|true
argument_list|)
expr_stmt|;
name|frm
operator|.
name|getDatePatternPrefs
argument_list|()
operator|.
name|clear
argument_list|()
expr_stmt|;
name|frm
operator|.
name|getDatePatternPrefLevels
argument_list|()
operator|.
name|clear
argument_list|()
expr_stmt|;
name|DatePattern
name|selectedDatePattern
init|=
operator|(
name|frm
operator|.
name|getDatePattern
argument_list|()
operator|<
literal|0
condition|?
name|c
operator|.
name|getSchedulingSubpart
argument_list|()
operator|.
name|effectiveDatePattern
argument_list|()
else|:
name|DatePatternDAO
operator|.
name|getInstance
argument_list|()
operator|.
name|get
argument_list|(
name|frm
operator|.
name|getDatePattern
argument_list|()
argument_list|)
operator|)
decl_stmt|;
if|if
condition|(
name|selectedDatePattern
operator|!=
literal|null
condition|)
block|{
for|for
control|(
name|DatePattern
name|dp
range|:
name|selectedDatePattern
operator|.
name|findChildren
argument_list|()
control|)
block|{
name|boolean
name|found
init|=
literal|false
decl_stmt|;
for|for
control|(
name|DatePatternPref
name|dpp
range|:
operator|(
name|Set
argument_list|<
name|DatePatternPref
argument_list|>
operator|)
name|c
operator|.
name|getPreferences
argument_list|(
name|DatePatternPref
operator|.
name|class
argument_list|)
control|)
block|{
if|if
condition|(
name|dp
operator|.
name|equals
argument_list|(
name|dpp
operator|.
name|getDatePattern
argument_list|()
argument_list|)
condition|)
block|{
name|frm
operator|.
name|addToDatePatternPrefs
argument_list|(
name|dp
operator|.
name|getUniqueId
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|,
name|dpp
operator|.
name|getPrefLevel
argument_list|()
operator|.
name|getUniqueId
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
name|found
operator|=
literal|true
expr_stmt|;
block|}
block|}
if|if
condition|(
operator|!
name|found
condition|)
for|for
control|(
name|DatePatternPref
name|dpp
range|:
operator|(
name|Set
argument_list|<
name|DatePatternPref
argument_list|>
operator|)
name|c
operator|.
name|getSchedulingSubpart
argument_list|()
operator|.
name|getPreferences
argument_list|(
name|DatePatternPref
operator|.
name|class
argument_list|)
control|)
block|{
if|if
condition|(
name|dp
operator|.
name|equals
argument_list|(
name|dpp
operator|.
name|getDatePattern
argument_list|()
argument_list|)
condition|)
block|{
name|frm
operator|.
name|addToDatePatternPrefs
argument_list|(
name|dp
operator|.
name|getUniqueId
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|,
name|dpp
operator|.
name|getPrefLevel
argument_list|()
operator|.
name|getUniqueId
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
name|found
operator|=
literal|true
expr_stmt|;
block|}
block|}
if|if
condition|(
operator|!
name|found
condition|)
name|frm
operator|.
name|addToDatePatternPrefs
argument_list|(
name|dp
operator|.
name|getUniqueId
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|,
name|PreferenceLevel
operator|.
name|PREF_LEVEL_NEUTRAL
argument_list|)
expr_stmt|;
block|}
block|}
block|}
comment|// Initialize Preferences for initial load
name|frm
operator|.
name|setAvailableTimePatterns
argument_list|(
name|TimePattern
operator|.
name|findApplicable
argument_list|(
name|sessionContext
operator|.
name|getUser
argument_list|()
argument_list|,
name|c
operator|.
name|getSchedulingSubpart
argument_list|()
operator|.
name|getMinutesPerWk
argument_list|()
argument_list|,
operator|(
name|frm
operator|.
name|getDatePattern
argument_list|()
operator|<
literal|0
condition|?
name|c
operator|.
name|getSchedulingSubpart
argument_list|()
operator|.
name|effectiveDatePattern
argument_list|()
else|:
name|DatePatternDAO
operator|.
name|getInstance
argument_list|()
operator|.
name|get
argument_list|(
name|frm
operator|.
name|getDatePattern
argument_list|()
argument_list|)
operator|)
argument_list|,
name|c
operator|.
name|getSchedulingSubpart
argument_list|()
operator|.
name|getInstrOfferingConfig
argument_list|()
operator|.
name|getDurationModel
argument_list|()
argument_list|,
literal|true
argument_list|,
name|c
operator|.
name|getManagingDept
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|Set
name|timePatterns
init|=
literal|null
decl_stmt|;
if|if
condition|(
name|op
operator|.
name|equals
argument_list|(
literal|"init"
argument_list|)
condition|)
block|{
name|initPrefs
argument_list|(
name|frm
argument_list|,
name|c
argument_list|,
name|leadInstructors
argument_list|,
literal|true
argument_list|)
expr_stmt|;
name|timePatterns
operator|=
name|c
operator|.
name|effectiveTimePatterns
argument_list|()
expr_stmt|;
name|DatePattern
name|selectedDatePattern
init|=
name|c
operator|.
name|effectiveDatePattern
argument_list|()
decl_stmt|;
if|if
condition|(
name|selectedDatePattern
operator|!=
literal|null
condition|)
block|{
for|for
control|(
name|DatePattern
name|dp
range|:
name|selectedDatePattern
operator|.
name|findChildren
argument_list|()
control|)
block|{
if|if
condition|(
operator|!
name|frm
operator|.
name|getDatePatternPrefs
argument_list|()
operator|.
name|contains
argument_list|(
name|dp
operator|.
name|getUniqueId
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
condition|)
block|{
name|frm
operator|.
name|addToDatePatternPrefs
argument_list|(
name|dp
operator|.
name|getUniqueId
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|,
name|PreferenceLevel
operator|.
name|PREF_LEVEL_NEUTRAL
argument_list|)
expr_stmt|;
block|}
block|}
block|}
block|}
comment|// Process Preferences Action
name|processPrefAction
argument_list|(
name|request
argument_list|,
name|frm
argument_list|,
name|errors
argument_list|)
expr_stmt|;
comment|// Generate Time Pattern Grids
name|super
operator|.
name|generateTimePatternGrids
argument_list|(
name|request
argument_list|,
name|frm
argument_list|,
name|c
argument_list|,
name|c
operator|.
name|getSchedulingSubpart
argument_list|()
operator|.
name|getMinutesPerWk
argument_list|()
argument_list|,
name|c
operator|.
name|getSchedulingSubpart
argument_list|()
operator|.
name|getInstrOfferingConfig
argument_list|()
operator|.
name|getDurationModel
argument_list|()
argument_list|,
operator|(
name|frm
operator|.
name|getDatePattern
argument_list|()
operator|<
literal|0
condition|?
name|c
operator|.
name|getSchedulingSubpart
argument_list|()
operator|.
name|effectiveDatePattern
argument_list|()
else|:
name|DatePatternDAO
operator|.
name|getInstance
argument_list|()
operator|.
name|get
argument_list|(
name|frm
operator|.
name|getDatePattern
argument_list|()
argument_list|)
operator|)
argument_list|,
name|timePatterns
argument_list|,
name|op
argument_list|,
name|timeVertical
argument_list|,
literal|true
argument_list|,
name|leadInstructors
argument_list|)
expr_stmt|;
comment|// Instructors
name|setupInstructors
argument_list|(
name|request
argument_list|,
name|frm
argument_list|,
name|c
argument_list|)
expr_stmt|;
name|setupChildren
argument_list|(
name|frm
argument_list|,
name|request
argument_list|,
name|c
argument_list|)
expr_stmt|;
comment|// Date patterns allowed in the DDL for Date pattern preferences
name|LookupTables
operator|.
name|setupDatePatterns
argument_list|(
name|request
argument_list|,
name|sessionContext
operator|.
name|getUser
argument_list|()
argument_list|,
name|MSG
operator|.
name|dropDefaultDatePattern
argument_list|()
argument_list|,
name|c
operator|.
name|getSchedulingSubpart
argument_list|()
operator|.
name|effectiveDatePattern
argument_list|()
argument_list|,
name|c
operator|.
name|getManagingDept
argument_list|()
argument_list|,
name|c
operator|.
name|effectiveDatePattern
argument_list|()
argument_list|)
expr_stmt|;
name|LookupTables
operator|.
name|setupRooms
argument_list|(
name|request
argument_list|,
name|c
argument_list|)
expr_stmt|;
comment|// Rooms
name|LookupTables
operator|.
name|setupBldgs
argument_list|(
name|request
argument_list|,
name|c
argument_list|)
expr_stmt|;
comment|// Buildings
name|LookupTables
operator|.
name|setupRoomFeatures
argument_list|(
name|request
argument_list|,
name|c
argument_list|)
expr_stmt|;
comment|// Room Features
name|LookupTables
operator|.
name|setupRoomGroups
argument_list|(
name|request
argument_list|,
name|c
argument_list|)
expr_stmt|;
comment|// Room Groups
name|frm
operator|.
name|setAllowHardPrefs
argument_list|(
name|sessionContext
operator|.
name|hasPermission
argument_list|(
name|c
argument_list|,
name|Right
operator|.
name|CanUseHardRoomPrefs
argument_list|)
argument_list|)
expr_stmt|;
name|BackTracker
operator|.
name|markForBack
argument_list|(
name|request
argument_list|,
literal|"classDetail.do?cid="
operator|+
name|frm
operator|.
name|getClassId
argument_list|()
argument_list|,
name|MSG
operator|.
name|backClass
argument_list|(
name|frm
operator|.
name|getClassName
argument_list|()
argument_list|)
argument_list|,
literal|true
argument_list|,
literal|false
argument_list|)
expr_stmt|;
return|return
name|mapping
operator|.
name|findForward
argument_list|(
literal|"editClass"
argument_list|)
return|;
block|}
catch|catch
parameter_list|(
name|Exception
name|e
parameter_list|)
block|{
name|Debug
operator|.
name|error
argument_list|(
name|e
argument_list|)
expr_stmt|;
throw|throw
name|e
throw|;
block|}
block|}
comment|/**      * Loads class info into the form      * @param request      * @param frm      * @param c      * @param classId      */
specifier|private
name|void
name|doLoad
parameter_list|(
name|HttpServletRequest
name|request
parameter_list|,
name|ClassEditForm
name|frm
parameter_list|,
name|Class_
name|c
parameter_list|,
name|String
name|op
parameter_list|)
block|{
name|Department
name|managingDept
init|=
name|c
operator|.
name|getManagingDept
argument_list|()
decl_stmt|;
name|String
name|parentClassName
init|=
literal|"-"
decl_stmt|;
name|Long
name|parentClassId
init|=
literal|null
decl_stmt|;
if|if
condition|(
name|c
operator|.
name|getParentClass
argument_list|()
operator|!=
literal|null
condition|)
block|{
name|parentClassName
operator|=
name|c
operator|.
name|getParentClass
argument_list|()
operator|.
name|toString
argument_list|()
expr_stmt|;
name|parentClassId
operator|=
name|c
operator|.
name|getParentClass
argument_list|()
operator|.
name|getUniqueId
argument_list|()
expr_stmt|;
block|}
name|CourseOffering
name|cco
init|=
name|c
operator|.
name|getSchedulingSubpart
argument_list|()
operator|.
name|getControllingCourseOffering
argument_list|()
decl_stmt|;
comment|// populate form
name|frm
operator|.
name|setClassId
argument_list|(
name|c
operator|.
name|getUniqueId
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setSection
argument_list|(
name|c
operator|.
name|getSectionNumberString
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setClassName
argument_list|(
name|c
operator|.
name|getClassLabel
argument_list|()
argument_list|)
expr_stmt|;
name|SchedulingSubpart
name|ss
init|=
name|c
operator|.
name|getSchedulingSubpart
argument_list|()
decl_stmt|;
name|String
name|itypeDesc
init|=
name|c
operator|.
name|getItypeDesc
argument_list|()
decl_stmt|;
if|if
condition|(
name|ss
operator|.
name|getInstrOfferingConfig
argument_list|()
operator|.
name|getInstructionalOffering
argument_list|()
operator|.
name|hasMultipleConfigurations
argument_list|()
condition|)
name|itypeDesc
operator|+=
literal|" ["
operator|+
name|ss
operator|.
name|getInstrOfferingConfig
argument_list|()
operator|.
name|getName
argument_list|()
operator|+
literal|"]"
expr_stmt|;
name|frm
operator|.
name|setItypeDesc
argument_list|(
name|itypeDesc
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setParentClassName
argument_list|(
name|parentClassName
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setParentClassId
argument_list|(
name|parentClassId
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setSubjectAreaId
argument_list|(
name|cco
operator|.
name|getSubjectArea
argument_list|()
operator|.
name|getUniqueId
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setInstrOfferingId
argument_list|(
name|cco
operator|.
name|getInstructionalOffering
argument_list|()
operator|.
name|getUniqueId
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setSubpart
argument_list|(
name|c
operator|.
name|getSchedulingSubpart
argument_list|()
operator|.
name|getUniqueId
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setCourseName
argument_list|(
name|cco
operator|.
name|getInstructionalOffering
argument_list|()
operator|.
name|getCourseName
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setCourseTitle
argument_list|(
name|cco
operator|.
name|getTitle
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setManagingDept
argument_list|(
name|managingDept
operator|.
name|getUniqueId
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setControllingDept
argument_list|(
name|c
operator|.
name|getControllingDept
argument_list|()
operator|.
name|getUniqueId
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setManagingDeptLabel
argument_list|(
name|managingDept
operator|.
name|getManagingDeptLabel
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setUnlimitedEnroll
argument_list|(
name|c
operator|.
name|getSchedulingSubpart
argument_list|()
operator|.
name|getInstrOfferingConfig
argument_list|()
operator|.
name|isUnlimitedEnrollment
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setAccommodation
argument_list|(
name|StudentAccomodation
operator|.
name|toHtml
argument_list|(
name|StudentAccomodation
operator|.
name|getAccommodations
argument_list|(
name|c
argument_list|)
argument_list|)
argument_list|)
expr_stmt|;
name|Class_
name|next
init|=
name|c
operator|.
name|getNextClass
argument_list|(
name|sessionContext
argument_list|,
name|Right
operator|.
name|ClassEdit
argument_list|)
decl_stmt|;
name|frm
operator|.
name|setNextId
argument_list|(
name|next
operator|==
literal|null
condition|?
literal|null
else|:
name|next
operator|.
name|getUniqueId
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
name|Class_
name|previous
init|=
name|c
operator|.
name|getPreviousClass
argument_list|(
name|sessionContext
argument_list|,
name|Right
operator|.
name|ClassEdit
argument_list|)
decl_stmt|;
name|frm
operator|.
name|setPreviousId
argument_list|(
name|previous
operator|==
literal|null
condition|?
literal|null
else|:
name|previous
operator|.
name|getUniqueId
argument_list|()
operator|.
name|toString
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setMinRoomLimit
argument_list|(
name|c
operator|.
name|getMinRoomLimit
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setEnrollment
argument_list|(
name|c
operator|.
name|getEnrollment
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setSnapshotLimit
argument_list|(
name|c
operator|.
name|getSnapshotLimit
argument_list|()
argument_list|)
expr_stmt|;
comment|// Load from class only for initial load or reload
if|if
condition|(
name|op
operator|.
name|equals
argument_list|(
literal|"init"
argument_list|)
condition|)
block|{
name|frm
operator|.
name|setExpectedCapacity
argument_list|(
name|c
operator|.
name|getExpectedCapacity
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setDatePattern
argument_list|(
name|c
operator|.
name|getDatePattern
argument_list|()
operator|==
literal|null
condition|?
name|Long
operator|.
name|valueOf
argument_list|(
operator|-
literal|1
argument_list|)
else|:
name|c
operator|.
name|getDatePattern
argument_list|()
operator|.
name|getUniqueId
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setNbrRooms
argument_list|(
name|c
operator|.
name|getNbrRooms
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setNotes
argument_list|(
name|c
operator|.
name|getNotes
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setManagingDept
argument_list|(
name|c
operator|.
name|getManagingDept
argument_list|()
operator|.
name|getUniqueId
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setSchedulePrintNote
argument_list|(
name|c
operator|.
name|getSchedulePrintNote
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setClassSuffix
argument_list|(
name|c
operator|.
name|getDivSecNumber
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setMaxExpectedCapacity
argument_list|(
name|c
operator|.
name|getMaxExpectedCapacity
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setRoomRatio
argument_list|(
name|c
operator|.
name|getRoomRatio
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setLms
argument_list|(
name|c
operator|.
name|getLms
argument_list|()
operator|==
literal|null
condition|?
literal|""
else|:
name|c
operator|.
name|getLms
argument_list|()
operator|.
name|getLabel
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setEnabledForStudentScheduling
argument_list|(
name|c
operator|.
name|isEnabledForStudentScheduling
argument_list|()
argument_list|)
expr_stmt|;
name|frm
operator|.
name|setDisplayInstructor
argument_list|(
name|c
operator|.
name|isDisplayInstructor
argument_list|()
argument_list|)
expr_stmt|;
name|List
name|instructors
init|=
operator|new
name|ArrayList
argument_list|(
name|c
operator|.
name|getClassInstructors
argument_list|()
argument_list|)
decl_stmt|;
name|Collections
operator|.
name|sort
argument_list|(
name|instructors
argument_list|,
operator|new
name|InstructorComparator
argument_list|()
argument_list|)
expr_stmt|;
for|for
control|(
name|Iterator
name|iter
init|=
name|instructors
operator|.
name|iterator
argument_list|()
init|;
name|iter
operator|.
name|hasNext
argument_list|()
condition|;
control|)
block|{
name|ClassInstructor
name|classInstr
init|=
operator|(
name|ClassInstructor
operator|)
name|iter
operator|.
name|next
argument_list|()
decl_stmt|;
name|frm
operator|.
name|addToInstructors
argument_list|(
name|classInstr
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|instructors
operator|.
name|isEmpty
argument_list|()
condition|)
name|frm
operator|.
name|addToInstructors
argument_list|(
literal|null
argument_list|)
expr_stmt|;
block|}
block|}
comment|/**      * Update class data      * @param request      * @param frm      */
specifier|private
name|void
name|doUpdate
parameter_list|(
name|HttpServletRequest
name|request
parameter_list|,
name|ClassEditForm
name|frm
parameter_list|,
name|Class_
name|c
parameter_list|,
name|org
operator|.
name|hibernate
operator|.
name|Session
name|hibSession
parameter_list|)
throws|throws
name|Exception
block|{
name|c
operator|.
name|setExpectedCapacity
argument_list|(
name|frm
operator|.
name|getExpectedCapacity
argument_list|()
argument_list|)
expr_stmt|;
if|if
condition|(
name|frm
operator|.
name|getDatePattern
argument_list|()
operator|==
literal|null
operator|||
name|frm
operator|.
name|getDatePattern
argument_list|()
operator|.
name|intValue
argument_list|()
operator|<
literal|0
condition|)
name|c
operator|.
name|setDatePattern
argument_list|(
literal|null
argument_list|)
expr_stmt|;
else|else
name|c
operator|.
name|setDatePattern
argument_list|(
operator|new
name|DatePatternDAO
argument_list|()
operator|.
name|get
argument_list|(
name|frm
operator|.
name|getDatePattern
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
name|c
operator|.
name|setNbrRooms
argument_list|(
name|frm
operator|.
name|getNbrRooms
argument_list|()
argument_list|)
expr_stmt|;
name|c
operator|.
name|setNotes
argument_list|(
name|frm
operator|.
name|getNotes
argument_list|()
argument_list|)
expr_stmt|;
name|c
operator|.
name|setSchedulePrintNote
argument_list|(
name|frm
operator|.
name|getSchedulePrintNote
argument_list|()
argument_list|)
expr_stmt|;
comment|//c.setClassSuffix(frm.getClassSuffix());
name|c
operator|.
name|setMaxExpectedCapacity
argument_list|(
name|frm
operator|.
name|getMaxExpectedCapacity
argument_list|()
argument_list|)
expr_stmt|;
name|c
operator|.
name|setRoomRatio
argument_list|(
name|frm
operator|.
name|getRoomRatio
argument_list|()
argument_list|)
expr_stmt|;
name|Boolean
name|disb
init|=
name|frm
operator|.
name|getEnabledForStudentScheduling
argument_list|()
decl_stmt|;
name|c
operator|.
name|setEnabledForStudentScheduling
argument_list|(
name|disb
operator|==
literal|null
condition|?
name|Boolean
operator|.
name|valueOf
argument_list|(
literal|false
argument_list|)
else|:
name|disb
argument_list|)
expr_stmt|;
name|Boolean
name|di
init|=
name|frm
operator|.
name|getDisplayInstructor
argument_list|()
decl_stmt|;
name|c
operator|.
name|setDisplayInstructor
argument_list|(
name|di
operator|==
literal|null
condition|?
name|Boolean
operator|.
name|valueOf
argument_list|(
literal|false
argument_list|)
else|:
name|di
argument_list|)
expr_stmt|;
name|boolean
name|assignTeachingRequest
init|=
name|Department
operator|.
name|isInstructorSchedulingCommitted
argument_list|(
name|c
operator|.
name|getControllingDept
argument_list|()
operator|.
name|getUniqueId
argument_list|()
argument_list|)
decl_stmt|;
comment|// Class all instructors
name|Set
argument_list|<
name|ClassInstructor
argument_list|>
name|classInstrs
init|=
operator|new
name|HashSet
argument_list|<
name|ClassInstructor
argument_list|>
argument_list|(
name|c
operator|.
name|getClassInstructors
argument_list|()
argument_list|)
decl_stmt|;
comment|// Get instructor data
name|List
name|instrLead
init|=
name|frm
operator|.
name|getInstrLead
argument_list|()
decl_stmt|;
name|List
name|instructors
init|=
name|frm
operator|.
name|getInstructors
argument_list|()
decl_stmt|;
name|List
name|instrPctShare
init|=
name|frm
operator|.
name|getInstrPctShare
argument_list|()
decl_stmt|;
name|List
name|instrResponsibility
init|=
name|frm
operator|.
name|getInstrResponsibility
argument_list|()
decl_stmt|;
comment|// Save instructor data to class
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|instructors
operator|.
name|size
argument_list|()
condition|;
name|i
operator|++
control|)
block|{
name|String
name|instrId
init|=
name|instructors
operator|.
name|get
argument_list|(
name|i
argument_list|)
operator|.
name|toString
argument_list|()
decl_stmt|;
if|if
condition|(
name|Preference
operator|.
name|BLANK_PREF_VALUE
operator|.
name|equals
argument_list|(
name|instrId
argument_list|)
condition|)
continue|continue;
name|String
name|pctShare
init|=
name|instrPctShare
operator|.
name|get
argument_list|(
name|i
argument_list|)
operator|.
name|toString
argument_list|()
decl_stmt|;
name|boolean
name|lead
init|=
literal|"on"
operator|.
name|equals
argument_list|(
name|instrLead
operator|.
name|get
argument_list|(
name|i
argument_list|)
argument_list|)
decl_stmt|;
name|String
name|resp
init|=
name|instrResponsibility
operator|.
name|get
argument_list|(
name|i
argument_list|)
operator|.
name|toString
argument_list|()
decl_stmt|;
name|DepartmentalInstructor
name|deptInstr
init|=
operator|new
name|DepartmentalInstructorDAO
argument_list|()
operator|.
name|get
argument_list|(
name|Long
operator|.
name|valueOf
argument_list|(
name|instrId
argument_list|)
argument_list|)
decl_stmt|;
name|ClassInstructor
name|classInstr
init|=
literal|null
decl_stmt|;
for|for
control|(
name|Iterator
argument_list|<
name|ClassInstructor
argument_list|>
name|j
init|=
name|classInstrs
operator|.
name|iterator
argument_list|()
init|;
name|j
operator|.
name|hasNext
argument_list|()
condition|;
control|)
block|{
name|ClassInstructor
name|adept
init|=
name|j
operator|.
name|next
argument_list|()
decl_stmt|;
if|if
condition|(
name|adept
operator|.
name|getInstructor
argument_list|()
operator|.
name|equals
argument_list|(
name|deptInstr
argument_list|)
condition|)
block|{
name|classInstr
operator|=
name|adept
expr_stmt|;
name|j
operator|.
name|remove
argument_list|()
expr_stmt|;
break|break;
block|}
block|}
if|if
condition|(
name|classInstr
operator|==
literal|null
condition|)
block|{
name|classInstr
operator|=
operator|new
name|ClassInstructor
argument_list|()
expr_stmt|;
name|classInstr
operator|.
name|setClassInstructing
argument_list|(
name|c
argument_list|)
expr_stmt|;
name|classInstr
operator|.
name|setInstructor
argument_list|(
name|deptInstr
argument_list|)
expr_stmt|;
name|deptInstr
operator|.
name|getClasses
argument_list|()
operator|.
name|add
argument_list|(
name|classInstr
argument_list|)
expr_stmt|;
name|c
operator|.
name|getClassInstructors
argument_list|()
operator|.
name|add
argument_list|(
name|classInstr
argument_list|)
expr_stmt|;
if|if
condition|(
name|assignTeachingRequest
condition|)
block|{
for|for
control|(
name|TeachingClassRequest
name|tcr
range|:
name|c
operator|.
name|getTeachingRequests
argument_list|()
control|)
block|{
if|if
condition|(
name|tcr
operator|.
name|getAssignInstructor
argument_list|()
operator|&&
name|tcr
operator|.
name|getTeachingRequest
argument_list|()
operator|.
name|getAssignedInstructors
argument_list|()
operator|.
name|contains
argument_list|(
name|deptInstr
argument_list|)
condition|)
block|{
name|classInstr
operator|.
name|setTeachingRequest
argument_list|(
name|tcr
operator|.
name|getTeachingRequest
argument_list|()
argument_list|)
expr_stmt|;
break|break;
block|}
block|}
block|}
block|}
name|classInstr
operator|.
name|setLead
argument_list|(
name|Boolean
operator|.
name|valueOf
argument_list|(
name|lead
argument_list|)
argument_list|)
expr_stmt|;
try|try
block|{
name|classInstr
operator|.
name|setPercentShare
argument_list|(
name|Integer
operator|.
name|valueOf
argument_list|(
name|pctShare
argument_list|)
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|NumberFormatException
name|e
parameter_list|)
block|{
name|classInstr
operator|.
name|setPercentShare
argument_list|(
name|Integer
operator|.
name|valueOf
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
block|}
try|try
block|{
name|classInstr
operator|.
name|setResponsibility
argument_list|(
name|TeachingResponsibilityDAO
operator|.
name|getInstance
argument_list|()
operator|.
name|get
argument_list|(
name|Long
operator|.
name|valueOf
argument_list|(
name|resp
argument_list|)
argument_list|,
name|hibSession
argument_list|)
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|NumberFormatException
name|e
parameter_list|)
block|{
name|classInstr
operator|.
name|setResponsibility
argument_list|(
literal|null
argument_list|)
expr_stmt|;
block|}
name|hibSession
operator|.
name|saveOrUpdate
argument_list|(
name|deptInstr
argument_list|)
expr_stmt|;
block|}
for|for
control|(
name|Iterator
argument_list|<
name|ClassInstructor
argument_list|>
name|iter
init|=
name|classInstrs
operator|.
name|iterator
argument_list|()
init|;
name|iter
operator|.
name|hasNext
argument_list|()
condition|;
control|)
block|{
name|ClassInstructor
name|ci
init|=
name|iter
operator|.
name|next
argument_list|()
decl_stmt|;
name|DepartmentalInstructor
name|instr
init|=
name|ci
operator|.
name|getInstructor
argument_list|()
decl_stmt|;
name|instr
operator|.
name|getClasses
argument_list|()
operator|.
name|remove
argument_list|(
name|ci
argument_list|)
expr_stmt|;
name|c
operator|.
name|getClassInstructors
argument_list|()
operator|.
name|remove
argument_list|(
name|ci
argument_list|)
expr_stmt|;
name|hibSession
operator|.
name|saveOrUpdate
argument_list|(
name|instr
argument_list|)
expr_stmt|;
name|hibSession
operator|.
name|delete
argument_list|(
name|ci
argument_list|)
expr_stmt|;
block|}
name|ChangeLog
operator|.
name|addChange
argument_list|(
name|hibSession
argument_list|,
name|sessionContext
argument_list|,
name|c
argument_list|,
name|ChangeLog
operator|.
name|Source
operator|.
name|CLASS_EDIT
argument_list|,
name|ChangeLog
operator|.
name|Operation
operator|.
name|UPDATE
argument_list|,
name|c
operator|.
name|getSchedulingSubpart
argument_list|()
operator|.
name|getInstrOfferingConfig
argument_list|()
operator|.
name|getControllingCourseOffering
argument_list|()
operator|.
name|getSubjectArea
argument_list|()
argument_list|,
name|c
operator|.
name|getManagingDept
argument_list|()
argument_list|)
expr_stmt|;
block|}
comment|/**      * Set up instructor lists      * @param request      * @param frm      * @param errors      */
specifier|protected
name|void
name|setupInstructors
parameter_list|(
name|HttpServletRequest
name|request
parameter_list|,
name|ClassEditForm
name|frm
parameter_list|,
name|Class_
name|c
parameter_list|)
throws|throws
name|Exception
block|{
name|List
name|instructors
init|=
name|frm
operator|.
name|getInstructors
argument_list|()
decl_stmt|;
if|if
condition|(
name|instructors
operator|.
name|size
argument_list|()
operator|==
literal|0
condition|)
return|return;
comment|// Get dept instructor list
name|LookupTables
operator|.
name|setupInstructors
argument_list|(
name|request
argument_list|,
name|sessionContext
argument_list|,
name|c
operator|.
name|getDepartmentForSubjectArea
argument_list|()
operator|.
name|getUniqueId
argument_list|()
argument_list|)
expr_stmt|;
name|LookupTables
operator|.
name|setupInstructorTeachingResponsibilities
argument_list|(
name|request
argument_list|)
expr_stmt|;
name|Vector
name|deptInstrList
init|=
operator|(
name|Vector
operator|)
name|request
operator|.
name|getAttribute
argument_list|(
name|DepartmentalInstructor
operator|.
name|INSTR_LIST_ATTR_NAME
argument_list|)
decl_stmt|;
comment|// For each instructor set the instructor list
for|for
control|(
name|int
name|i
init|=
literal|0
init|;
name|i
operator|<
name|instructors
operator|.
name|size
argument_list|()
condition|;
name|i
operator|++
control|)
block|{
name|request
operator|.
name|setAttribute
argument_list|(
name|DepartmentalInstructor
operator|.
name|INSTR_LIST_ATTR_NAME
operator|+
name|i
argument_list|,
name|deptInstrList
argument_list|)
expr_stmt|;
block|}
block|}
comment|/**      * Add an instructor to the list (UI)      * @param request      * @param frm      * @param errors      */
specifier|protected
name|void
name|addInstructor
parameter_list|(
name|HttpServletRequest
name|request
parameter_list|,
name|ClassEditForm
name|frm
parameter_list|,
name|ActionMessages
name|errors
parameter_list|)
block|{
if|if
condition|(
name|request
operator|.
name|getParameter
argument_list|(
literal|"instrListTypeAction"
argument_list|)
operator|!=
literal|null
operator|&&
name|request
operator|.
name|getParameter
argument_list|(
literal|"instrListTypeAction"
argument_list|)
operator|.
name|toString
argument_list|()
operator|.
name|length
argument_list|()
operator|>
literal|0
condition|)
return|return;
name|frm
operator|.
name|addToInstructors
argument_list|(
literal|null
argument_list|)
expr_stmt|;
name|request
operator|.
name|setAttribute
argument_list|(
name|HASH_ATTR
argument_list|,
name|HASH_INSTRUCTORS
argument_list|)
expr_stmt|;
block|}
comment|/**      * Deletes an instructor from the list (UI)      * @param request      * @param frm      */
specifier|protected
name|void
name|deleteInstructor
parameter_list|(
name|HttpServletRequest
name|request
parameter_list|,
name|ClassEditForm
name|frm
parameter_list|)
block|{
name|int
name|deleteId
init|=
operator|-
literal|1
decl_stmt|;
try|try
block|{
name|deleteId
operator|=
name|Integer
operator|.
name|parseInt
argument_list|(
name|request
operator|.
name|getParameter
argument_list|(
literal|"deleteId"
argument_list|)
argument_list|)
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|Exception
name|e
parameter_list|)
block|{
name|deleteId
operator|=
operator|-
literal|1
expr_stmt|;
block|}
if|if
condition|(
name|deleteId
operator|>=
literal|0
condition|)
block|{
name|frm
operator|.
name|removeInstructor
argument_list|(
name|deleteId
argument_list|)
expr_stmt|;
name|request
operator|.
name|setAttribute
argument_list|(
name|HASH_ATTR
argument_list|,
name|HASH_INSTRUCTORS
argument_list|)
expr_stmt|;
block|}
block|}
comment|/**      * This method is called to setup children of the selected date pattern of the class      * or the selected date pattern of the scheduling subpart of the current class.      *       * @param frm ClassEditForm      * @param request HttpServletRequest      * @param c Class_      * @throws Exception       */
specifier|protected
name|void
name|setupChildren
parameter_list|(
name|ClassEditForm
name|frm
parameter_list|,
name|HttpServletRequest
name|request
parameter_list|,
name|Class_
name|c
parameter_list|)
throws|throws
name|Exception
block|{
name|DatePattern
name|selectedDatePattern
init|=
operator|(
name|frm
operator|.
name|getDatePattern
argument_list|()
operator|<
literal|0
condition|?
name|c
operator|.
name|getSchedulingSubpart
argument_list|()
operator|.
name|effectiveDatePattern
argument_list|()
else|:
name|DatePatternDAO
operator|.
name|getInstance
argument_list|()
operator|.
name|get
argument_list|(
name|frm
operator|.
name|getDatePattern
argument_list|()
argument_list|)
operator|)
decl_stmt|;
if|if
condition|(
name|selectedDatePattern
operator|!=
literal|null
condition|)
block|{
name|List
argument_list|<
name|DatePattern
argument_list|>
name|v
init|=
name|selectedDatePattern
operator|.
name|findChildren
argument_list|()
decl_stmt|;
name|request
operator|.
name|setAttribute
argument_list|(
name|DatePattern
operator|.
name|DATE_PATTERN_CHILDREN_LIST_ATTR
argument_list|,
name|v
argument_list|)
expr_stmt|;
name|frm
operator|.
name|sortDatePatternPrefs
argument_list|(
name|frm
operator|.
name|getDatePatternPrefs
argument_list|()
argument_list|,
name|frm
operator|.
name|getDatePatternPrefLevels
argument_list|()
argument_list|,
name|v
argument_list|)
expr_stmt|;
block|}
block|}
block|}
end_class

end_unit

