begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * UniTime 3.4 - 3.5 (University Timetabling Application)  * Copyright (C) 2013, UniTime LLC, and individual contributors  * as indicated by the @authors tag.  *   * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 3 of the License, or  * (at your option) any later version.  *   * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *   * You should have received a copy of the GNU General Public License along  * with this program.  If not, see<http://www.gnu.org/licenses/>.  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|gwt
operator|.
name|client
operator|.
name|aria
package|;
end_package

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gwt
operator|.
name|aria
operator|.
name|client
operator|.
name|Id
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gwt
operator|.
name|aria
operator|.
name|client
operator|.
name|Roles
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gwt
operator|.
name|user
operator|.
name|client
operator|.
name|DOM
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gwt
operator|.
name|user
operator|.
name|client
operator|.
name|ui
operator|.
name|DialogBox
import|;
end_import

begin_comment
comment|/**  * @author Tomas Muller  */
end_comment

begin_class
specifier|public
class|class
name|AriaDialogBox
extends|extends
name|DialogBox
block|{
specifier|public
name|AriaDialogBox
parameter_list|(
name|boolean
name|autoHide
parameter_list|,
name|boolean
name|modal
parameter_list|,
name|Caption
name|caption
parameter_list|)
block|{
name|super
argument_list|(
name|autoHide
argument_list|,
name|modal
argument_list|,
name|caption
argument_list|)
expr_stmt|;
name|Roles
operator|.
name|getDialogRole
argument_list|()
operator|.
name|set
argument_list|(
name|getElement
argument_list|()
argument_list|)
expr_stmt|;
name|caption
operator|.
name|asWidget
argument_list|()
operator|.
name|getElement
argument_list|()
operator|.
name|setId
argument_list|(
name|DOM
operator|.
name|createUniqueId
argument_list|()
argument_list|)
expr_stmt|;
name|Roles
operator|.
name|getDialogRole
argument_list|()
operator|.
name|setAriaLabelledbyProperty
argument_list|(
name|getElement
argument_list|()
argument_list|,
name|Id
operator|.
name|of
argument_list|(
name|caption
operator|.
name|asWidget
argument_list|()
operator|.
name|getElement
argument_list|()
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|public
name|AriaDialogBox
parameter_list|(
name|boolean
name|autoHide
parameter_list|,
name|boolean
name|modal
parameter_list|)
block|{
name|this
argument_list|(
name|autoHide
argument_list|,
name|modal
argument_list|,
operator|new
name|CaptionImpl
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|AriaDialogBox
parameter_list|(
name|boolean
name|autoHide
parameter_list|)
block|{
name|this
argument_list|(
name|autoHide
argument_list|,
literal|true
argument_list|,
operator|new
name|CaptionImpl
argument_list|()
argument_list|)
expr_stmt|;
block|}
specifier|public
name|AriaDialogBox
parameter_list|()
block|{
name|this
argument_list|(
literal|false
argument_list|,
literal|true
argument_list|,
operator|new
name|CaptionImpl
argument_list|()
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

