begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * UniTime 3.5 (University Timetabling Application)  * Copyright (C) 2014, UniTime LLC, and individual contributors  * as indicated by the @authors tag.  *   * This program is free software; you can redistribute it and/or modify  * it under the terms of the GNU General Public License as published by  * the Free Software Foundation; either version 3 of the License, or  * (at your option) any later version.  *   * This program is distributed in the hope that it will be useful,  * but WITHOUT ANY WARRANTY; without even the implied warranty of  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  * GNU General Public License for more details.  *   * You should have received a copy of the GNU General Public License along  * with this program.  If not, see<http://www.gnu.org/licenses/>.  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|gwt
operator|.
name|mobile
operator|.
name|client
package|;
end_package

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|gwt
operator|.
name|mobile
operator|.
name|client
operator|.
name|page
operator|.
name|MobileMenu
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|gwt
operator|.
name|mobile
operator|.
name|client
operator|.
name|page
operator|.
name|ReportFormFactor
import|;
end_import

begin_import
import|import
name|com
operator|.
name|google
operator|.
name|gwt
operator|.
name|user
operator|.
name|client
operator|.
name|ui
operator|.
name|RootPanel
import|;
end_import

begin_comment
comment|/**  * @author Tomas Muller  */
end_comment

begin_enum
specifier|public
enum|enum
name|MobileComponents
block|{
name|detectFormFactor
argument_list|(
literal|"UniTimeGWT:DetectFormFactor"
argument_list|,
operator|new
name|ComponentFactory
argument_list|()
block|{
specifier|public
name|void
name|insert
parameter_list|(
name|RootPanel
name|panel
parameter_list|)
block|{
name|ReportFormFactor
operator|.
name|report
argument_list|(
name|panel
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
block|,
name|menubar_mobile
argument_list|(
literal|"UniTimeGWT:MobileMenu"
argument_list|,
operator|new
name|ComponentFactory
argument_list|()
block|{
specifier|public
name|void
name|insert
parameter_list|(
name|RootPanel
name|panel
parameter_list|)
block|{
operator|new
name|MobileMenu
argument_list|()
operator|.
name|insert
argument_list|(
name|panel
argument_list|)
expr_stmt|;
block|}
block|}
argument_list|)
block|, 	;
specifier|private
name|String
name|iId
decl_stmt|;
specifier|private
name|ComponentFactory
name|iFactory
decl_stmt|;
specifier|private
name|boolean
name|iMultiple
init|=
literal|false
decl_stmt|;
name|MobileComponents
parameter_list|(
name|String
name|id
parameter_list|,
name|ComponentFactory
name|factory
parameter_list|)
block|{
name|iId
operator|=
name|id
expr_stmt|;
name|iFactory
operator|=
name|factory
expr_stmt|;
block|}
name|MobileComponents
parameter_list|(
name|String
name|id
parameter_list|,
name|boolean
name|multiple
parameter_list|,
name|ComponentFactory
name|factory
parameter_list|)
block|{
name|iId
operator|=
name|id
expr_stmt|;
name|iFactory
operator|=
name|factory
expr_stmt|;
name|iMultiple
operator|=
name|multiple
expr_stmt|;
block|}
specifier|public
name|String
name|id
parameter_list|()
block|{
return|return
name|iId
return|;
block|}
specifier|public
name|void
name|insert
parameter_list|(
name|RootPanel
name|panel
parameter_list|)
block|{
name|iFactory
operator|.
name|insert
argument_list|(
name|panel
argument_list|)
expr_stmt|;
block|}
specifier|public
name|boolean
name|isMultiple
parameter_list|()
block|{
return|return
name|iMultiple
return|;
block|}
specifier|public
interface|interface
name|ComponentFactory
block|{
name|void
name|insert
parameter_list|(
name|RootPanel
name|panel
parameter_list|)
function_decl|;
block|}
block|}
end_enum

end_unit

