begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to The Apereo Foundation under one or more contributor license  * agreements. See the NOTICE file distributed with this work for  * additional information regarding copyright ownership.  *  * The Apereo Foundation licenses this file to you under the Apache License,  * Version 2.0 (the "License"); you may not use this file except in  * compliance with the License. You may obtain a copy of the License at:  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *  * See the License for the specific language governing permissions and  * limitations under the License.  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|server
operator|.
name|hql
package|;
end_package

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|beans
operator|.
name|factory
operator|.
name|annotation
operator|.
name|Autowired
import|;
end_import

begin_import
import|import
name|org
operator|.
name|springframework
operator|.
name|security
operator|.
name|access
operator|.
name|prepost
operator|.
name|PreAuthorize
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|localization
operator|.
name|impl
operator|.
name|Localization
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|gwt
operator|.
name|command
operator|.
name|client
operator|.
name|GwtRpcResponseNull
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|gwt
operator|.
name|command
operator|.
name|server
operator|.
name|GwtRpcImplementation
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|gwt
operator|.
name|command
operator|.
name|server
operator|.
name|GwtRpcImplements
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|gwt
operator|.
name|resources
operator|.
name|GwtMessages
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|gwt
operator|.
name|shared
operator|.
name|SavedHQLInterface
operator|.
name|HQLSetBackRpcRequest
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|SavedHQL
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|security
operator|.
name|SessionContext
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|webutil
operator|.
name|BackTracker
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|webutil
operator|.
name|Navigation
import|;
end_import

begin_comment
comment|/**  * @author Tomas Muller  */
end_comment

begin_class
annotation|@
name|GwtRpcImplements
argument_list|(
name|HQLSetBackRpcRequest
operator|.
name|class
argument_list|)
specifier|public
class|class
name|HQLSetBackBackend
implements|implements
name|GwtRpcImplementation
argument_list|<
name|HQLSetBackRpcRequest
argument_list|,
name|GwtRpcResponseNull
argument_list|>
block|{
specifier|protected
specifier|static
name|GwtMessages
name|MESSAGES
init|=
name|Localization
operator|.
name|create
argument_list|(
name|GwtMessages
operator|.
name|class
argument_list|)
decl_stmt|;
annotation|@
name|Autowired
specifier|private
name|SessionContext
name|sessionContext
decl_stmt|;
annotation|@
name|Override
annotation|@
name|PreAuthorize
argument_list|(
literal|"checkPermission('HQLReports')"
argument_list|)
specifier|public
name|GwtRpcResponseNull
name|execute
parameter_list|(
name|HQLSetBackRpcRequest
name|request
parameter_list|,
name|SessionContext
name|context
parameter_list|)
block|{
name|String
name|title
init|=
name|MESSAGES
operator|.
name|pageCourseReports
argument_list|()
decl_stmt|;
switch|switch
condition|(
name|getAppearanceFlag
argument_list|(
name|request
operator|.
name|getAppearance
argument_list|()
argument_list|)
condition|)
block|{
case|case
name|APPEARANCE_COURSES
case|:
name|title
operator|=
name|MESSAGES
operator|.
name|pageCourseReports
argument_list|()
expr_stmt|;
break|break;
case|case
name|APPEARANCE_EXAMS
case|:
name|title
operator|=
name|MESSAGES
operator|.
name|pageExaminationReports
argument_list|()
expr_stmt|;
break|break;
case|case
name|APPEARANCE_SECTIONING
case|:
name|title
operator|=
name|MESSAGES
operator|.
name|pageStudentSectioningReports
argument_list|()
expr_stmt|;
break|break;
case|case
name|APPEARANCE_EVENTS
case|:
name|title
operator|=
name|MESSAGES
operator|.
name|pageEventReports
argument_list|()
expr_stmt|;
break|break;
case|case
name|APPEARANCE_ADMINISTRATION
case|:
name|title
operator|=
name|MESSAGES
operator|.
name|pageAdministrationReports
argument_list|()
expr_stmt|;
break|break;
block|}
name|BackTracker
operator|.
name|markForBack
argument_list|(
name|sessionContext
argument_list|,
literal|"gwt.jsp?page=hql&appearance="
operator|+
name|request
operator|.
name|getAppearance
argument_list|()
operator|+
literal|"#"
operator|+
name|request
operator|.
name|getHistory
argument_list|()
argument_list|,
name|title
argument_list|,
literal|true
argument_list|,
literal|true
argument_list|)
expr_stmt|;
if|if
condition|(
literal|"__Class"
operator|.
name|equals
argument_list|(
name|request
operator|.
name|getType
argument_list|()
argument_list|)
condition|)
name|Navigation
operator|.
name|set
argument_list|(
name|sessionContext
argument_list|,
name|Navigation
operator|.
name|sClassLevel
argument_list|,
name|request
operator|.
name|getIds
argument_list|()
argument_list|)
expr_stmt|;
if|else if
condition|(
literal|"__Offering"
operator|.
name|equals
argument_list|(
name|request
operator|.
name|getType
argument_list|()
argument_list|)
condition|)
name|Navigation
operator|.
name|set
argument_list|(
name|sessionContext
argument_list|,
name|Navigation
operator|.
name|sInstructionalOfferingLevel
argument_list|,
name|request
operator|.
name|getIds
argument_list|()
argument_list|)
expr_stmt|;
if|else if
condition|(
literal|"__Subpart"
operator|.
name|equals
argument_list|(
name|request
operator|.
name|getType
argument_list|()
argument_list|)
condition|)
name|Navigation
operator|.
name|set
argument_list|(
name|sessionContext
argument_list|,
name|Navigation
operator|.
name|sSchedulingSubpartLevel
argument_list|,
name|request
operator|.
name|getIds
argument_list|()
argument_list|)
expr_stmt|;
if|else if
condition|(
literal|"__Room"
operator|.
name|equals
argument_list|(
name|request
operator|.
name|getType
argument_list|()
argument_list|)
condition|)
name|Navigation
operator|.
name|set
argument_list|(
name|sessionContext
argument_list|,
name|Navigation
operator|.
name|sInstructionalOfferingLevel
argument_list|,
name|request
operator|.
name|getIds
argument_list|()
argument_list|)
expr_stmt|;
if|else if
condition|(
literal|"__Instructor"
operator|.
name|equals
argument_list|(
name|request
operator|.
name|getType
argument_list|()
argument_list|)
condition|)
name|Navigation
operator|.
name|set
argument_list|(
name|sessionContext
argument_list|,
name|Navigation
operator|.
name|sInstructionalOfferingLevel
argument_list|,
name|request
operator|.
name|getIds
argument_list|()
argument_list|)
expr_stmt|;
if|else if
condition|(
literal|"__Exam"
operator|.
name|equals
argument_list|(
name|request
operator|.
name|getType
argument_list|()
argument_list|)
condition|)
name|Navigation
operator|.
name|set
argument_list|(
name|sessionContext
argument_list|,
name|Navigation
operator|.
name|sInstructionalOfferingLevel
argument_list|,
name|request
operator|.
name|getIds
argument_list|()
argument_list|)
expr_stmt|;
if|else if
condition|(
literal|"__Event"
operator|.
name|equals
argument_list|(
name|request
operator|.
name|getType
argument_list|()
argument_list|)
condition|)
name|Navigation
operator|.
name|set
argument_list|(
name|sessionContext
argument_list|,
name|Navigation
operator|.
name|sInstructionalOfferingLevel
argument_list|,
name|request
operator|.
name|getIds
argument_list|()
argument_list|)
expr_stmt|;
return|return
literal|null
return|;
block|}
specifier|private
name|SavedHQL
operator|.
name|Flag
name|getAppearanceFlag
parameter_list|(
name|String
name|appearance
parameter_list|)
block|{
for|for
control|(
name|SavedHQL
operator|.
name|Flag
name|flag
range|:
name|SavedHQL
operator|.
name|Flag
operator|.
name|values
argument_list|()
control|)
if|if
condition|(
name|flag
operator|.
name|getAppearance
argument_list|()
operator|!=
literal|null
operator|&&
name|flag
operator|.
name|getAppearance
argument_list|()
operator|.
name|equalsIgnoreCase
argument_list|(
name|appearance
argument_list|)
condition|)
return|return
name|flag
return|;
return|return
name|SavedHQL
operator|.
name|Flag
operator|.
name|APPEARANCE_COURSES
return|;
block|}
block|}
end_class

end_unit

