begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to The Apereo Foundation under one or more contributor license  * agreements. See the NOTICE file distributed with this work for  * additional information regarding copyright ownership.  *  * The Apereo Foundation licenses this file to you under the Apache License,  * Version 2.0 (the "License"); you may not use this file except in  * compliance with the License. You may obtain a copy of the License at:  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *  * See the License for the specific language governing permissions and  * limitations under the License.  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|base
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|Serializable
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|HashSet
import|;
end_import

begin_import
import|import
name|java
operator|.
name|util
operator|.
name|Set
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|Building
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|EventServiceProvider
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|Location
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|Room
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|RoomPicture
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|RoomType
import|;
end_import

begin_comment
comment|/**  * Do not change this class. It has been automatically generated using ant create-model.  * @see org.unitime.commons.ant.CreateBaseModelFromXml  */
end_comment

begin_class
specifier|public
specifier|abstract
class|class
name|BaseRoom
extends|extends
name|Location
implements|implements
name|Serializable
block|{
specifier|private
specifier|static
specifier|final
name|long
name|serialVersionUID
init|=
literal|1L
decl_stmt|;
specifier|private
name|String
name|iBuildingAbbv
decl_stmt|;
specifier|private
name|String
name|iRoomNumber
decl_stmt|;
specifier|private
name|String
name|iClassification
decl_stmt|;
specifier|private
name|RoomType
name|iRoomType
decl_stmt|;
specifier|private
name|Building
name|iBuilding
decl_stmt|;
specifier|private
name|Room
name|iParentRoom
decl_stmt|;
specifier|private
name|Set
argument_list|<
name|RoomPicture
argument_list|>
name|iPictures
decl_stmt|;
specifier|private
name|Set
argument_list|<
name|EventServiceProvider
argument_list|>
name|iAllowedServices
decl_stmt|;
specifier|private
name|Set
argument_list|<
name|Room
argument_list|>
name|iPartitions
decl_stmt|;
specifier|public
specifier|static
name|String
name|PROP_ROOM_NUMBER
init|=
literal|"roomNumber"
decl_stmt|;
specifier|public
specifier|static
name|String
name|PROP_CLASSIFICATION
init|=
literal|"classification"
decl_stmt|;
specifier|public
name|BaseRoom
parameter_list|()
block|{
name|initialize
argument_list|()
expr_stmt|;
block|}
specifier|public
name|BaseRoom
parameter_list|(
name|Long
name|uniqueId
parameter_list|)
block|{
name|setUniqueId
argument_list|(
name|uniqueId
argument_list|)
expr_stmt|;
name|initialize
argument_list|()
expr_stmt|;
block|}
specifier|protected
name|void
name|initialize
parameter_list|()
block|{
block|}
specifier|public
name|String
name|getBuildingAbbv
parameter_list|()
block|{
return|return
name|iBuildingAbbv
return|;
block|}
specifier|public
name|void
name|setBuildingAbbv
parameter_list|(
name|String
name|buildingAbbv
parameter_list|)
block|{
name|iBuildingAbbv
operator|=
name|buildingAbbv
expr_stmt|;
block|}
specifier|public
name|String
name|getRoomNumber
parameter_list|()
block|{
return|return
name|iRoomNumber
return|;
block|}
specifier|public
name|void
name|setRoomNumber
parameter_list|(
name|String
name|roomNumber
parameter_list|)
block|{
name|iRoomNumber
operator|=
name|roomNumber
expr_stmt|;
block|}
specifier|public
name|String
name|getClassification
parameter_list|()
block|{
return|return
name|iClassification
return|;
block|}
specifier|public
name|void
name|setClassification
parameter_list|(
name|String
name|classification
parameter_list|)
block|{
name|iClassification
operator|=
name|classification
expr_stmt|;
block|}
specifier|public
name|RoomType
name|getRoomType
parameter_list|()
block|{
return|return
name|iRoomType
return|;
block|}
specifier|public
name|void
name|setRoomType
parameter_list|(
name|RoomType
name|roomType
parameter_list|)
block|{
name|iRoomType
operator|=
name|roomType
expr_stmt|;
block|}
specifier|public
name|Building
name|getBuilding
parameter_list|()
block|{
return|return
name|iBuilding
return|;
block|}
specifier|public
name|void
name|setBuilding
parameter_list|(
name|Building
name|building
parameter_list|)
block|{
name|iBuilding
operator|=
name|building
expr_stmt|;
block|}
specifier|public
name|Room
name|getParentRoom
parameter_list|()
block|{
return|return
name|iParentRoom
return|;
block|}
specifier|public
name|void
name|setParentRoom
parameter_list|(
name|Room
name|parentRoom
parameter_list|)
block|{
name|iParentRoom
operator|=
name|parentRoom
expr_stmt|;
block|}
specifier|public
name|Set
argument_list|<
name|RoomPicture
argument_list|>
name|getPictures
parameter_list|()
block|{
return|return
name|iPictures
return|;
block|}
specifier|public
name|void
name|setPictures
parameter_list|(
name|Set
argument_list|<
name|RoomPicture
argument_list|>
name|pictures
parameter_list|)
block|{
name|iPictures
operator|=
name|pictures
expr_stmt|;
block|}
specifier|public
name|void
name|addTopictures
parameter_list|(
name|RoomPicture
name|roomPicture
parameter_list|)
block|{
if|if
condition|(
name|iPictures
operator|==
literal|null
condition|)
name|iPictures
operator|=
operator|new
name|HashSet
argument_list|<
name|RoomPicture
argument_list|>
argument_list|()
expr_stmt|;
name|iPictures
operator|.
name|add
argument_list|(
name|roomPicture
argument_list|)
expr_stmt|;
block|}
specifier|public
name|Set
argument_list|<
name|EventServiceProvider
argument_list|>
name|getAllowedServices
parameter_list|()
block|{
return|return
name|iAllowedServices
return|;
block|}
specifier|public
name|void
name|setAllowedServices
parameter_list|(
name|Set
argument_list|<
name|EventServiceProvider
argument_list|>
name|allowedServices
parameter_list|)
block|{
name|iAllowedServices
operator|=
name|allowedServices
expr_stmt|;
block|}
specifier|public
name|void
name|addToallowedServices
parameter_list|(
name|EventServiceProvider
name|eventServiceProvider
parameter_list|)
block|{
if|if
condition|(
name|iAllowedServices
operator|==
literal|null
condition|)
name|iAllowedServices
operator|=
operator|new
name|HashSet
argument_list|<
name|EventServiceProvider
argument_list|>
argument_list|()
expr_stmt|;
name|iAllowedServices
operator|.
name|add
argument_list|(
name|eventServiceProvider
argument_list|)
expr_stmt|;
block|}
specifier|public
name|Set
argument_list|<
name|Room
argument_list|>
name|getPartitions
parameter_list|()
block|{
return|return
name|iPartitions
return|;
block|}
specifier|public
name|void
name|setPartitions
parameter_list|(
name|Set
argument_list|<
name|Room
argument_list|>
name|partitions
parameter_list|)
block|{
name|iPartitions
operator|=
name|partitions
expr_stmt|;
block|}
specifier|public
name|void
name|addTopartitions
parameter_list|(
name|Room
name|room
parameter_list|)
block|{
if|if
condition|(
name|iPartitions
operator|==
literal|null
condition|)
name|iPartitions
operator|=
operator|new
name|HashSet
argument_list|<
name|Room
argument_list|>
argument_list|()
expr_stmt|;
name|iPartitions
operator|.
name|add
argument_list|(
name|room
argument_list|)
expr_stmt|;
block|}
specifier|public
name|boolean
name|equals
parameter_list|(
name|Object
name|o
parameter_list|)
block|{
if|if
condition|(
name|o
operator|==
literal|null
operator|||
operator|!
operator|(
name|o
operator|instanceof
name|Room
operator|)
condition|)
return|return
literal|false
return|;
if|if
condition|(
name|getUniqueId
argument_list|()
operator|==
literal|null
operator|||
operator|(
operator|(
name|Room
operator|)
name|o
operator|)
operator|.
name|getUniqueId
argument_list|()
operator|==
literal|null
condition|)
return|return
literal|false
return|;
return|return
name|getUniqueId
argument_list|()
operator|.
name|equals
argument_list|(
operator|(
operator|(
name|Room
operator|)
name|o
operator|)
operator|.
name|getUniqueId
argument_list|()
argument_list|)
return|;
block|}
specifier|public
name|int
name|hashCode
parameter_list|()
block|{
if|if
condition|(
name|getUniqueId
argument_list|()
operator|==
literal|null
condition|)
return|return
name|super
operator|.
name|hashCode
argument_list|()
return|;
return|return
name|getUniqueId
argument_list|()
operator|.
name|hashCode
argument_list|()
return|;
block|}
specifier|public
name|String
name|toString
parameter_list|()
block|{
return|return
literal|"Room["
operator|+
name|getUniqueId
argument_list|()
operator|+
literal|"]"
return|;
block|}
specifier|public
name|String
name|toDebugString
parameter_list|()
block|{
return|return
literal|"Room["
operator|+
literal|"\n	Area: "
operator|+
name|getArea
argument_list|()
operator|+
literal|"\n	BreakTime: "
operator|+
name|getBreakTime
argument_list|()
operator|+
literal|"\n	Building: "
operator|+
name|getBuilding
argument_list|()
operator|+
literal|"\n	Capacity: "
operator|+
name|getCapacity
argument_list|()
operator|+
literal|"\n	Classification: "
operator|+
name|getClassification
argument_list|()
operator|+
literal|"\n	CoordinateX: "
operator|+
name|getCoordinateX
argument_list|()
operator|+
literal|"\n	CoordinateY: "
operator|+
name|getCoordinateY
argument_list|()
operator|+
literal|"\n	DisplayName: "
operator|+
name|getDisplayName
argument_list|()
operator|+
literal|"\n	EventAvailability: "
operator|+
name|getEventAvailability
argument_list|()
operator|+
literal|"\n	EventDepartment: "
operator|+
name|getEventDepartment
argument_list|()
operator|+
literal|"\n	EventStatus: "
operator|+
name|getEventStatus
argument_list|()
operator|+
literal|"\n	ExamCapacity: "
operator|+
name|getExamCapacity
argument_list|()
operator|+
literal|"\n	ExternalUniqueId: "
operator|+
name|getExternalUniqueId
argument_list|()
operator|+
literal|"\n	IgnoreRoomCheck: "
operator|+
name|getIgnoreRoomCheck
argument_list|()
operator|+
literal|"\n	IgnoreTooFar: "
operator|+
name|getIgnoreTooFar
argument_list|()
operator|+
literal|"\n	ManagerIds: "
operator|+
name|getManagerIds
argument_list|()
operator|+
literal|"\n	Note: "
operator|+
name|getNote
argument_list|()
operator|+
literal|"\n	ParentRoom: "
operator|+
name|getParentRoom
argument_list|()
operator|+
literal|"\n	Pattern: "
operator|+
name|getPattern
argument_list|()
operator|+
literal|"\n	PermanentId: "
operator|+
name|getPermanentId
argument_list|()
operator|+
literal|"\n	RoomNumber: "
operator|+
name|getRoomNumber
argument_list|()
operator|+
literal|"\n	RoomType: "
operator|+
name|getRoomType
argument_list|()
operator|+
literal|"\n	Session: "
operator|+
name|getSession
argument_list|()
operator|+
literal|"\n	ShareNote: "
operator|+
name|getShareNote
argument_list|()
operator|+
literal|"\n	UniqueId: "
operator|+
name|getUniqueId
argument_list|()
operator|+
literal|"]"
return|;
block|}
block|}
end_class

end_unit

