begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_comment
comment|/*  * Licensed to The Apereo Foundation under one or more contributor license  * agreements. See the NOTICE file distributed with this work for  * additional information regarding copyright ownership.  *  * The Apereo Foundation licenses this file to you under the Apache License,  * Version 2.0 (the "License"); you may not use this file except in  * compliance with the License. You may obtain a copy of the License at:  *  * http://www.apache.org/licenses/LICENSE-2.0  *  * Unless required by applicable law or agreed to in writing, software  * distributed under the License is distributed on an "AS IS" BASIS,  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *  * See the License for the specific language governing permissions and  * limitations under the License.  *  */
end_comment

begin_package
package|package
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|util
package|;
end_package

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|interfaces
operator|.
name|AcademicSessionLookup
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|Session
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|SubjectArea
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|dao
operator|.
name|SessionDAO
import|;
end_import

begin_import
import|import
name|org
operator|.
name|unitime
operator|.
name|timetable
operator|.
name|model
operator|.
name|dao
operator|.
name|SubjectAreaDAO
import|;
end_import

begin_class
specifier|public
class|class
name|DefaultAcademicSessionLookup
implements|implements
name|AcademicSessionLookup
block|{
annotation|@
name|Override
specifier|public
name|Session
name|findAcademicSession
parameter_list|(
name|String
name|campus
parameter_list|,
name|String
name|year
parameter_list|,
name|String
name|term
parameter_list|,
name|org
operator|.
name|hibernate
operator|.
name|Session
name|hibSession
parameter_list|)
block|{
return|return
name|Session
operator|.
name|getSessionUsingInitiativeYearTerm
argument_list|(
name|campus
argument_list|,
name|year
argument_list|,
name|term
argument_list|,
name|hibSession
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|Session
name|findAcademicSession
parameter_list|(
name|String
name|campus
parameter_list|,
name|String
name|year
parameter_list|,
name|String
name|term
parameter_list|)
block|{
return|return
name|findAcademicSession
argument_list|(
name|campus
argument_list|,
name|year
argument_list|,
name|term
argument_list|,
name|SessionDAO
operator|.
name|getInstance
argument_list|()
operator|.
name|getSession
argument_list|()
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|SubjectArea
name|findSubjectAreaForCampusYearTerm
parameter_list|(
name|String
name|campus
parameter_list|,
name|String
name|year
parameter_list|,
name|String
name|term
parameter_list|,
name|String
name|subjectAreaAbbreviation
parameter_list|,
name|org
operator|.
name|hibernate
operator|.
name|Session
name|hibSession
parameter_list|)
block|{
return|return
name|SubjectArea
operator|.
name|findUsingInitiativeYearTermSubjectAbbreviation
argument_list|(
name|campus
argument_list|,
name|year
argument_list|,
name|term
argument_list|,
name|subjectAreaAbbreviation
argument_list|,
name|hibSession
argument_list|)
return|;
block|}
annotation|@
name|Override
specifier|public
name|SubjectArea
name|findSubjectAreaForCampusYearTerm
parameter_list|(
name|String
name|campus
parameter_list|,
name|String
name|year
parameter_list|,
name|String
name|term
parameter_list|,
name|String
name|subjectAreaAbbreviation
parameter_list|)
block|{
return|return
name|findSubjectAreaForCampusYearTerm
argument_list|(
name|campus
argument_list|,
name|year
argument_list|,
name|term
argument_list|,
name|subjectAreaAbbreviation
argument_list|,
name|SubjectAreaDAO
operator|.
name|getInstance
argument_list|()
operator|.
name|getSession
argument_list|()
argument_list|)
return|;
block|}
block|}
end_class

end_unit

